<div class="sidebarmenu">
                 <a class="menuitem_green" href="recordsale.php">Record Sale</a>
          <a class="menuitem submenuheader" href="">Inventory</a>
      <div class="submenu">
                    <ul>
                    <li><a href="addproductcategory.php">New Product Category</a></li>
        	    <li><a href="addproduct.php">New Product</a></li>
                    <li><a href="restock.php">Re-stock Product</a></li>
                    <li><a href="removeproduct.php">Remove Product</a></li>
                    <li><a href="viewstocklevel.php">View Stock Levels</a></li>
		    <li><a href="modifyproduct.php">Modify Product</a></li>
</ul>
                </div>
                <a class="menuitem submenuheader" href="" >HR Manager</a>
                <div class="submenu">
                    <ul>
                    <li><a href="addpersonnel.php">Add Personnel</a></li>
                    <li><a href="viewstaff.php">View Staff Record</a></li>
                    <li><a href="modifystaff.php">Modify Staff Record</a></li>
		    <li><a href="deletestaffrecord.php">Delete Staff Record</a></li>
                    <li><a href="viewincentive.php">View/Pay Current Staff Incentive</a></li>
		    <li><a href="viewpaidincentive.php">View Paid Incentive</a></li>
                  </ul>
                </div>
                <a class="menuitem submenuheader" href="">View Sales Record</a>
                <div class="submenu">
                    <ul>
                    <li><a href="dailysales.php">Daily</a></li>
                    <li><a href="monthlysales.php">Monthly</a></li>
                    <li><a href="annualsales.php">Annual</a></li>
		    <li><a href="salesrange.php">Date Range</a></li>
		    <li><a href="productsales.php">Product Sales Report</a></li>
                    </ul>
                </div>

		<a class="menuitem submenuheader" href="">Expenses</a>
                <div class="submenu">
                    <ul>
                    <li><a href="addexpenses.php">Add Expenses</a></li>
                    <li><a href="viewexpenses.php">View Expenses</a></li>
                   </ul>
                </div>


		<a class="menuitem submenuheader" href="">Debts</a>
                <div class="submenu">
                    <ul>
                    <li><a href="adddebt.php">Add Debt</a></li>
                    <li><a href="viewdebt.php">View Debts</a></li>
		<li><a href="settledebt.php">Settle Debts</a></li>

                   </ul>
                </div>

                 <a class="menuitem submenuheader" href="">Manage Users</a>
                <div class="submenu">
                    <ul>
                    <li><a href="newuser.php">Create a New User</a></li>
	            <li><a href="viewusers.php">View Users</a></li>
                    <li><a href="deleteuser.php">Delete User</a></li>
                    
                    </ul>
</div>
                
                
                <a class="menuitem_green" href="support.php">User Guide</a>

                    
            </div>