 <div class="center_content"> 
<div class="left_content">
      
         <?php include($nav);?>
            
            <div class="sidebar_box">
                <div class="sidebar_box_top"></div>
                <div class="sidebar_box_content">
                <h3>App Info</h3>
                <img src="images/info.png" alt="" title="" class="sidebar_icon_right" />
                <p>
Bizap is a HR/Sales management web application developed by TAVICOM. Version 1.0.1 currently has a Sales, HR, Inventory and Admin module. Newer versions will include additional modules.</p>                
                </div>
                <div class="sidebar_box_bottom"></div>
            </div>
            
            <div class="sidebar_box">
                <div class="sidebar_box_top"></div>
                <div class="sidebar_box_content">
                <h4>Important notice</h4>
                <img src="images/notice.png" alt="" title="" class="sidebar_icon_right" />
                <p>
This application requires internet connection to function properly. Ensure that you have an active connection when storing or retrieving records.
                </p>                
                </div>
                <div class="sidebar_box_bottom"></div>
            </div>
            <div class="sidebar_box">
            <div class="sidebar_box_top"></div>
                <div class="sidebar_box_content">
                <h3>Support</h3>
                <img src="images/help.png" alt="" title="" class="sidebar_icon_right" /><br />
                <br />
<br />
                  For assistance or support call
                  <ul>
                 <li>08035840779<br />
                   <br />
                 </li>
                   
                   or send an email to<br />
                   <br />
<li>support@tavicom.com</li>
                </ul>                
                </div>
                <div class="sidebar_box_bottom"></div>
            </div>
              
    
    </div>