<div class="menu">
                    <ul>
                    <li><a class="current" href="dashboard.php">Dashboard</a></li>
                    <li><a href="#">Manage User Account<!--[if IE 7]><!--></a><!--<![endif]-->
                    <!--[if lte IE 6]><table><tr><td><![endif]-->
                        <ul>
                        <li><a href="changepword.php" title="">Change Password</a></li>
                       
                       </ul>
                    <!--[if lte IE 6]></td></tr></table></a><![endif]-->
                    </li>
                    <li><a href="#">Customer Service<!--[if IE 7]><!--></a><!--<![endif]-->
                    <!--[if lte IE 6]><table><tr><td><![endif]-->
                        <ul>
                        <li><a href="registeramember.php" title="">Add a Customer</a></li>
                        <li><a href="viewmembers.php" title="">View Customer's Record</a></li>
                        
                    
                        
                        </ul>
                    <!--[if lte IE 6]></td></tr></table></a><![endif]-->
                    </li>
                    <li><a href="support.php">Support</a></li>
                    </ul>
                    </div>