<div class="sidebarmenu">
                 <a class="menuitem_green" href="recordsale.php">Record Sale</a>
          <a class="menuitem submenuheader" href="">Inventory</a>
      <div class="submenu">
                    <ul>
                    <li><a href="viewstocklevel2.php">View Stock Levels</a></li>

</ul>
                </div>
     
               <a class="menuitem_green" href="support.php">User Guide</a>

                    
            </div>